theme = "ananke"
staticDir = ["static"]

[languages]
  [languages.en]
    baseURL = "https://ridephysics.com"
    languageName = "English"
    staticDir2 = "static_en"
    title = "RidePhysics"
    weight = 2
    googleAnalytics = "UA-162502035-1"
    youtube = "https://www.youtube.com/channel/UCFKTmIilhqp_Ypack64r5Zg"

  [languages.de]
    baseURL = "https://kirmesphysik.de"
    languageName = "Deutsch"
    staticDir2 = "static_de"
    title = "KirmesPhysik"
    weight = 1
    googleAnalytics = "UA-162502035-2"
    youtube = "https://www.youtube.com/channel/UCD9FH6RjCzhshDW82N1zziQ"

[params]
github = "https://github.com/ridephysics"